# EC2 Instance Manifest - Crossplane
# This creates an EC2 instance in the production VPC with proper networking

---
# EC2 Instance
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: crossplane-prod-ec2-1
spec:
  forProvider:
    region: us-east-1
    instanceType: t3.micro  # Free tier eligible
    ami: ami-0de716d6197524dd9  # Amazon Linux 2023 (us-east-1)
    # keyName: crossplane-prod-key  # Optional: if you have a key pair
    subnetIdRef:
      name: crossplane-prod-public-subnet-1  # Deploy in public subnet for easier access
    vpcSecurityGroupIds:
      - sg-01aeeb3d8d0067b41  # Use the actual security group ID
    userData: |
      #!/bin/bash
      sudo dnf update -y
      sudo dnf install httpd   -y
      sudo systemctl start httpd
      sudo systemctl enable httpd
      echo "<h1>Hello from Crossplane EC2 with HTTPD!</h1>" > /var/www/html/index.html
      echo "<p>Instance deployed by Crossplane in VPC: crossplane-prod-vpc</p>" >> /var/www/html/index.html
      echo "<p>Deployed at: $(date)</p>" >> /var/www/html/index.html
      echo "<p>Web Server: HTTPD</p>" >> /var/www/html/index.html
    tags:
      Name: "Crossplane Production EC2 Instance 1"
      Purpose: "Web Server Demo"
      Environment: "Production"
      ManagedBy: "Crossplane"
      Project: "guiadodevops"
      Owner: "DevOps Team"
      Type: "Web Server"
      InstanceType: "t3.micro"
      AMI: "Amazon Linux 2023"
  providerConfigRef:
    name: default

---
# Key Pair (Optional - uncomment if you want SSH access)
# apiVersion: ec2.aws.upbound.io/v1beta1
# kind: KeyPair
# metadata:
#   name: crossplane-prod-key
# spec:
#   forProvider:
#     region: us-east-1
#     tags:
#       Name: "Crossplane Production Key Pair"
#       Purpose: "EC2 SSH Access"
#       Environment: "Production"
#       ManagedBy: "Crossplane"
#       Project: "guiadodevops"
#       Owner: "DevOps Team"
#   providerConfigRef:
#     name: default
