apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: boutique-tls
  namespace: istio-system
spec:
  secretName: tls-boutique
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - boutique.dublinconsulting.com.br

