apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-config
  namespace: argocd     
spec:
  project: core-tools-config
  source:
    repoURL: https://github.com/flaviorssilva1981/guiadodevops.git
    path: kubernetes/argocd_cluster02/config/core-tools/istio-config
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
