apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator-config
  namespace: argocd     
spec:
  project: core-tools
  source:
    repoURL: https://github.com/flaviorssilva1981/guiadodevops.git
    targetRevision: HEAD
    path: kubernetes/argocd_cluster02/config/core-tools/trivy-operator-config
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true 