apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-provider-cloudflare
  namespace: operational
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: external-dns-provider-cloudflare
  data:
    - secretKey: CF_API_KEY
      remoteRef:
        key: external-dns-provider-cloudflare
        property: CF_API_KEY
    - secretKey: CF_API_EMAIL
      remoteRef:
        key: external-dns-provider-cloudflare
        property: CF_API_EMAIL