# mesh-mtls.yaml
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata: { name: default, namespace: istio-system }
spec:
  mtls: { mode: STRICT }
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata: { name: default, namespace: istio-system }
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
