apiVersion: v1
kind: Service
metadata:
  name: frontend-active
  namespace: boutique
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-preview
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 8080
