apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-nonprod
  namespace: argocd
spec:
  project: nonprod
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 0.1.1
    helm:
      values: |-
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt"
          hosts:
            - host: myapp-nonprod.guiadodevops.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
          - secretName: myapp-nonprod-tls
            hosts:
              - myapp-nonprod.guiadodevops.com
    chart: prod/myapp
  destination:
    server: https://kubernetes.default.svc
    namespace: nonprod
  syncPolicy:
    automated: {}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true