apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-nonprod
  namespace: argocd
spec:
  project: nonprod
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 0.1.0
    chart: prod/myapp
  destination:
    server: https://kubernetes.default.svc
    namespace: nonprod
  syncPolicy:
    automated: {}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true