apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-nonprod
  namespace: argocd
spec:
  project: nonprod
  source:
    repoURL: guiadodevops.azurecr.io
    targetRevision: 25.0.1
    helm:
      values: |-
        service:
          type: ClusterIP
    chart: wordpress
  destination:
    server: https://kubernetes.default.svc
    namespace: nonprod
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
