apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd     
spec:
  project: infra-config
  source:
    repoURL: https://github.com/ndawpa/guiadodevops
    path: kubernetes/core-tools-config/argocd-config
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: operational
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
