apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd    
spec:
  project: infra
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.1.2
    helm:
      values: |-
        server:
          ingress:
            enabled: true
            hostname: argocd.guiadodevops.com
            annotations:
              kubernetes.io/ingress.class: "nginx"
              cert-manager.io/cluster-issuer: "letsencrypt"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            hosts:
              - argocd.guiadodevops.com
            paths:
              - /
            tls:
              - hosts:
                  - argocd.guiadodevops.com
                secretName: argocd-tls
        configs:
          cm:
            accounts.willian: apiKey,login
          secret:
            extra:
              willian.password: "$2a$10$835pvk9LZPA/vT4isSk6GuyQIuEWXnOktS8O2JNXJBv1fy.ZKNguy" 
    chart: argo-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
