apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd     
spec:
  project: infra
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.17.0
    chart: external-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: operational
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
