apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd     
spec:
  project: infra
  source:
    repoURL: https://charts.external-secrets.io/
    targetRevision: 0.18.2
    chart: external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
