apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd     
spec:
  project: infra
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 12.1.1
    chart: infra/gitea
  destination:
    server: https://kubernetes.default.svc
    namespace: operational
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
