apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd     
spec:
  project: infra
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 24.7.7
    chart: keycloak
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
