apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd     
spec:
  project: infra
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 75.9.0
    helm:
      values: |-
        crds:
          enabled: false
          upgradeJob:
            enabled: false
            forceConflicts: false
    chart: infra/kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
