apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd     
spec:
  project: infra
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.30.0
    helm:
      values: |-
        server:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: "letsencrypt"
              external-dns.alpha.kubernetes.io/hostname: guiadodevops.com
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
            hosts:
              - host: vault.guiadodevops.com
                paths:
                - "/"
            tls:
            - secretName: vault-tls
              hosts:
                - vault.guiadodevops.com
    chart: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
