annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: "Allow extraArgs to also be a map enabling overrides of individual values."
    - kind: changed
      description: "Update CRD."
    - kind: changed
      description: "Update CRD."
    - kind: changed
      description: "Update ExternalDNS OCI image version to v0.17.0."
    - kind: fixed
      description: "Fix wrong type definitions for webhook probes."
    - kind: fixed
      description: "Update schema with latest plugin release."
apiVersion: v2
appVersion: 0.17.0
description: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with
  DNS providers.
home: https://github.com/kubernetes-sigs/external-dns/
icon: https://github.com/kubernetes-sigs/external-dns/raw/master/docs/img/external-dns.png
keywords:
- kubernetes
- k8s
- externaldns
- external-dns
- dns
- service
- ingress
- gateway
maintainers:
- email: steve.hipwell@gmail.com
  name: stevehipwell
name: external-dns
sources:
- https://github.com/kubernetes-sigs/external-dns/
type: application
version: 1.17.0
