apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-crds
  namespace: argocd     
spec:
  project: core-tools
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 75.9.0
    helm:
      values: |-
        crds:
          enabled: true
        prometheus:
          enabled: false
        alertmanager:
          enabled: false
        grafana:
          enabled: false
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: false
    chart: infra/kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      allowEmpty: true 
      selfHeal: true 