apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd     
spec:
  project: core-tools
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 0.29.3
    chart: infra/trivy-operator
    helm:
      values: |-
        operator:
          metrics:
            enabled: true
          scanJobTimeout: 15m
          scanJobTTL: 1h
          scanJobsConcurrentLimit: 5
          scanJobsRetryDelay: 5m
          vulnerabilityScannerScanOnlyCurrentRevisions: true
          sbomGenerationEnabled: false
          scannerReportTTL: 24h
        trivyOperator:
          scanJobCompressLogs: true
          excludeImages: "quay.io/kiwigrid/k8s-sidecar:*"
        trivy:
          timeout: 15m0s
          slow: true
          severity: HIGH,CRITICAL
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 3Gi
        service:
          metricsPort: 8080
        prometheus:
          serviceMonitor:
            enabled: true
            namespace: monitoring
            interval: 30s
            labels:
              release: prometheus
          rules:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
