apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd     
spec:
  project: core-tools
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 0.30.0
    helm:
      values: |-
        server:
          ingress:
            enabled: true
            pathType: ImplementationSpecific
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: letsencrypt-prod
              cert-manager.io/common-name: vault.dublinconsulting.com.br
            hosts:
              - host: vault.dublinconsulting.com.br
                paths:
                - "/"
            tls:
              - secretName: vault-tls
                hosts:
                  - vault.dublinconsulting.com.br
    chart: infra/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jsonPointers:
        - /webhooks
