apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd     
spec:
  project: core-tools
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 0.30.0
    helm:
      values: |-
        server:
          ingress:
            enabled: true
            pathType: ImplementationSpecific
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
              - host: vault.local
                paths:
                - "/"
          ha:
            enabled: true
            replicas: 2
          serviceAccount:
            create: true
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
          persistence:
            enabled: true
            storageClass: "oci-bv"
            size: 10Gi
    chart: infra/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
