apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd     
spec:
  project: core-tools
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.30.0
    helm:
      values: |-
        server:
          ingress:
            enabled: true
            pathType: ImplementationSpecific
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
              - host: vault.local
                paths:
                - "/"
    chart: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
#remove pv policy      
