apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd     
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/ignore-differences: |
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        name: vault-agent-injector-cfg
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
spec:
  project: core-tools
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 0.30.0
    helm:
      values: |-
        server:
          ingress:
            enabled: true
            pathType: ImplementationSpecific
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
              - host: vault.local
                paths:
                - "/"
        injector:
          certs:
            secretName: null
            caBundle: ""
    chart: infra/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
#remove pv policy      
