apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-config
  namespace: argocd     
spec:
  project: infra-config
  source:
    repoURL: https://github.com/ndawpa/guiadodevops
    path: kubernetes/infra-configs/cert-manager-config
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
