apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-config
  namespace: argocd     
spec:
  project: infra-config
  source:
    repoURL: https://github.com/ndawpa/guiadodevops
    path: kubernetes/infra-configs/crossplane-config
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: operational
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
