apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd     
spec:
  project: infra
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 16.7.20
    chart: infra/postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: operational
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
