apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd     
spec:
  project: infra
  source:
    repoURL: harbor.guiadodevops.com
    targetRevision: 2.1.5
    chart: infra/reloader
  destination:
    server: https://kubernetes.default.svc
    namespace: operational
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
