apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repository-harbor
  namespace: argocd
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: argocd-repository-harbor
    namespace: argocd
    labels:
      argocd.argoproj.io/secret-type: repository
  dataFrom:
    - extract:
        key: argocd-repository-harbor