apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  namespace: security
spec:
  provider:
    vault:
      server: "https://vault.example.com"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: security